name: nimmala

on:
  push:
    branches:
      - main
    paths: 
      - '.module/vpc.tf'
  workflow_dispatch: 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
        - name: nimmala checkout repo
          uses: actions/checkout@v1

        - name: terraform subbu Init
          uses: hashicorp/terraform-github-actions/init@v0.4.0
          env:
           GITHUB_TOKEN: ${{ secrets.test_TOKEN }}
           TF_ACTION_WORKING_DIR: ./module
           AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#         - name: nimmala Validate
#           uses: hashicorp/terraform-github-actions/validate@v0.4.0

        - name: nimmala Apply
          uses: hashicorp/terraform-github-actions/apply@v0.4.0
          env:
           GITHUB_TOKEN: ${{ secrets.test_TOKEN }}
           TF_ACTION_WORKING_DIR: ./module
           AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    
 
